services:
    custom-rpi-image:
        build: .
        privileged: true
        stdin_open: true
        tty: true
        image: rpi-web-kiosk:latest
        volumes:
            - ./kaptive-arm64:/home/imagegen/kaptive-arm64
            - ./out:/tmp/kaptive-player-arm64/out